# Generated by Django 5.2.3 on 2025-08-25 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مشتری')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='شخص رابط')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماده')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('unit', models.CharField(default='کیلوگرم', max_length=20, verbose_name='واحد اندازه\u200cگیری')),
            ],
            options={
                'verbose_name': 'نوع ماده',
                'verbose_name_plural': 'انواع مواد',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'تامین\u200cکننده', 'verbose_name_plural': 'تامین\u200cکنندگان'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, verbose_name='شخص رابط'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='نام شرکت'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره تماس'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='موجودی فعلی')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نوع ماده')),
            ],
            options={
                'verbose_name': 'موجودی انبار',
                'verbose_name_plural': 'موجودی انبار',
                'unique_together': {('material_type',)},
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت کل')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ورود')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نوع ماده')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='تامین\u200cکننده')),
            ],
            options={
                'verbose_name': 'ورودی انبار',
                'verbose_name_plural': 'ورودی\u200cهای انبار',
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت واحد')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت کل')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='شماره فاکتور')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ خروج')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='مشتری')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نوع ماده')),
            ],
            options={
                'verbose_name': 'خروجی انبار',
                'verbose_name_plural': 'خروجی\u200cهای انبار',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('in', 'انتقال به انبار'), ('out', 'انتقال از انبار')], max_length=3, verbose_name='نوع انتقال')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدار')),
                ('source_location', models.CharField(max_length=100, verbose_name='مکان مبدا')),
                ('destination_location', models.CharField(max_length=100, verbose_name='مکان مقصد')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتقال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نوع ماده')),
            ],
            options={
                'verbose_name': 'انتقال انبار',
                'verbose_name_plural': 'انتقالات انبار',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
