# Generated by Django 5.2.5 on 2025-08-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_customer_materialtype_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_quantity',
            field=models.IntegerField(default=0, verbose_name='موجودی فعلی'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='total_price',
            field=models.IntegerField(verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='unit_price',
            field=models.IntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='quantity',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='total_price',
            field=models.IntegerField(verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='unit_price',
            field=models.IntegerField(verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.IntegerField(verbose_name='مقدار'),
        ),
    ]
