# Generated by Django 5.2.5 on 2025-08-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_current_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='current_quantity',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='موجودی فعلی'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='total_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='unit_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='مقدار'),
        ),
    ]
