# Generated by Django 5.2.5 on 2025-08-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventory_current_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'verbose_name': 'نام کالا', 'verbose_name_plural': 'نام\u200cهای کالا'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'هویت کالا', 'verbose_name_plural': 'هویت\u200cهای کالا'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.AddField(
            model_name='stockin',
            name='manual_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ ورود دستی'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='manual_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خروج دستی'),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره بارنامه'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='هویت کالا'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='شماره بارنامه'),
        ),
        migrations.AlterField(
            model_name='stockout',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialtype', verbose_name='نام کالا'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=200, verbose_name='هویت کالا'),
        ),
    ]
