# Generated by Django 5.2.5 on 2025-08-26 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_materialtype_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام انبار')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد انبار')),
                ('address', models.TextField(blank=True, verbose_name='آدرس انبار')),
                ('manager', models.CharField(blank=True, max_length=100, verbose_name='مدیر انبار')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='destination_location',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='source_location',
        ),
        migrations.RemoveField(
            model_name='stocktransfer',
            name='transfer_type',
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.warehouse', verbose_name='انبار'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='inventory.warehouse', verbose_name='انبار مقصد'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='inventory.warehouse', verbose_name='انبار مبدا'),
        ),
    ]
