# Generated by Django 5.2.5 on 2025-09-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_warehouse_alter_inventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='هویت کالا (Supplier)'),
        ),
        migrations.AddField(
            model_name='stockin',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.customer', verbose_name='مشتری (پیش\u200cفرض خودتان)'),
        ),
        migrations.AddField(
            model_name='stockout',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='هویت کالای خروجی (از کدام Supplier)'),
        ),
    ]
